version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5050:5050"
    volumes:
      - ../storage/mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5050
      --backend-store-uri file:/mlflow/mlruns
      --artifacts-destination file:/mlflow/mlruns/artifacts